name: ubuntu

on: 
  workflow_dispatch:
    inputs:
      authcode:
        description: 'cmd'
        required: true
  
jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v2
    - name: installing chrome remote desktop
      run: sh ./setup.sh
    - name: starting chrome remote desktop
      run: ${{ github.event.inputs.authcode }} -pin=123456
    - name: reboot
      run: sudo reboot
    - name: Keep Alive
      run: sleep infinity
